"use strict";

import React from "react";
import ReactDOM from "react-dom";

import Issue from "./issue.jsx";

ReactDOM.render(
	<Issue
		error="RXJyb3I6IHNhbXBsZSBlcnJvcgogICAgYXQgL2FwcC9pbmRleC5qczoxMzoyNAogICAgYXQgbmV4dCAobmF0aXZlKQogICAgYXQgcnVua2l0LXJ1bnRpbWU6MzEyMjo2NgogICAgYXQgbmV4dCAobmF0aXZlKQogICAgYXQgaXRlcmF0ZSAocnVua2l0LXJ1bnRpbWU6MzEzNjo3NykKICAgIGF0IG1vZHVsZS5leHBvcnRzIChydW5raXQtcnVudGltZTozMTUwOjE5KQogICAgYXQgcnVua2l0LXJ1bnRpbWU6MzIzMzo3CiAgICBhdCBydW5raXQtcnVudGltZTozMjM0OjMKICAgIGF0IE9iamVjdC48YW5vbnltb3VzPiAocnVua2l0LXJ1bnRpbWU6ODoxMCkKICAgIGF0IE1vZHVsZS5fY29tcGlsZSAobW9kdWxlLmpzOjU3MDozMikKICAgIGF0IE9iamVjdC5Nb2R1bGUuX2V4dGVuc2lvbnMuLmpzIChtb2R1bGUuanM6NTc5OjEwKQogICAgYXQgTW9kdWxlLmxvYWQgKG1vZHVsZS5qczo0ODc6MzIpCiAgICBhdCB0cnlNb2R1bGVMb2FkIChtb2R1bGUuanM6NDQ2OjEyKQogICAgYXQgRnVuY3Rpb24uTW9kdWxlLl9sb2FkIChtb2R1bGUuanM6NDM4OjMpCiAgICBhdCBNb2R1bGUucnVuTWFpbiAobW9kdWxlLmpzOjYwNDoxMCkKICAgIGF0IHJ1biAoYm9vdHN0cmFwX25vZGUuanM6Mzk0OjcpCiAgICBhdCBzdGFydHVwIChib290c3RyYXBfbm9kZS5qczoxNDk6OSkKICAgIGF0IGJvb3RzdHJhcF9ub2RlLmpzOjUwOToz"
		message="Sorry, this is a sample error. Testing only."
	>
	</Issue>,

	document.getElementById( "root" )
);
